# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist', '0002_runpython'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
