# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist', '0003_auto_20171118_0509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
