# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-22 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist', '0005_word_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='question_type',
            field=models.CharField(choices=[('W', 'Words'), ('S', 'Sentences')], default='W', max_length=1),
        ),
    ]
